### ISSUE TITLE
paredit-mode for inferior Scheme mode?

### ISSUE THREAD

**Issue by jasonhemann** [Lewis-Kelley/ez-macs#1]
IIRC, paredit isn't enabled at present for inferior scheme mode, so there's no paredit at the REPL. This is getting it resolved for me. 

````
(add-hook 'inferior-scheme-mode-hook               #'enable-paredit-mode)
````

I have also installed the package `paredit-everywhere`, though so I'm not sure which I'm taking advantage of.

**Comment by Lewis-Kelley** [comment]
Closed with 57dd811
